import { useState, useContext, createContext } from "react";

export const translations = {
  en: {
    appTagline: "Beauty · Fitness · Fashion",
    home: "Home", face: "Face", fitness: "Fitness", fashion: "Fashion", profile: "Profile",
    faceTitle: "Face Analysis", faceSubtitle: "Upload a selfie for AI-powered hairstyle recommendations",
    fitnessTitle: "AI Fitness Coach", fitnessSubtitle: "Personalized calorie & workout plan just for you",
    fashionTitle: "AI Fashion Advisor", fashionSubtitle: "Upload your photo for a personalized style makeover",
    uploadSelfie: "Upload your selfie", uploadBody: "Upload full body photo",
    analyzeBtn: "✨ Analyze My Face", generateBtn: "🏋️ Generate My Plan", styleBtn: "👗 Style Me Up",
    analyzing: "AI is analyzing your features...", building: "Building your personalized plan...", styling: "Your personal stylist is working...",
    bestHairstyles: "Best Hairstyles For You", colorRec: "Hair Color Recommendations",
    stylesAvoid: "Styles To Avoid", groomingTips: "Grooming Tips",
    dailyCalories: "Daily Calories", macros: "Daily Macros", proTips: "Pro Tips",
    perfectOutfits: "Perfect Outfits For You", colorPalette: "Your Color Palette",
    accessories: "Must-Have Accessories", brands: "Recommended Brands",
    welcomeBack: "Welcome back", yourJourney: "Journey",
    notificationsTitle: "Notifications", settingsTitle: "Settings",
    darkMode: "Dark Mode", lightMode: "Light Mode", language: "Language",
    workoutReminder: "Workout Reminder", waterReminder: "Water Reminder", progressReport: "Weekly Progress Report",
    enabled: "Enabled", disabled: "Disabled",
    occasion: "Select Occasion", casual: "Casual", office: "Office", party: "Party", wedding: "Wedding", gym: "Gym", date: "Date Night",
    goal: "Your Goal", weightLoss: "Lose Weight", muscle: "Build Muscle", weightGain: "Gain Weight", maintenance: "Stay Fit",
    age: "Age", weight: "Weight", height: "Height",
    signIn: "Sign In", signUp: "Sign Up", createAccount: "🚀 Create Account", signingIn: "Please wait...",
    signOut: "🚪 Sign Out", glowupMember: "✨ GlowUp Member",
    faceAnalyses: "Face Analyses", fitnessPlans: "Fitness Plans", fashionLooks: "Fashion Looks",
    fitnessProfile: "Fitness Profile",
  },
  hi: {
    appTagline: "सौंदर्य · फिटनेस · फैशन",
    home: "होम", face: "चेहरा", fitness: "फिटनेस", fashion: "फैशन", profile: "प्रोफाइल",
    faceTitle: "चेहरे का विश्लेषण", faceSubtitle: "AI हेयरस्टाइल सुझाव के लिए सेल्फी अपलोड करें",
    fitnessTitle: "AI फिटनेस कोच", fitnessSubtitle: "आपके लिए व्यक्तिगत कैलोरी और वर्कआउट प्लान",
    fashionTitle: "AI फैशन सलाहकार", fashionSubtitle: "व्यक्तिगत स्टाइल मेकओवर के लिए फोटो अपलोड करें",
    uploadSelfie: "अपनी सेल्फी अपलोड करें", uploadBody: "पूरे शरीर की फोटो अपलोड करें",
    analyzeBtn: "✨ चेहरे का विश्लेषण करें", generateBtn: "🏋️ प्लान बनाएं", styleBtn: "👗 स्टाइल करें",
    analyzing: "AI आपके चेहरे का विश्लेषण कर रहा है...", building: "आपका व्यक्तिगत प्लान बन रहा है...", styling: "आपका स्टाइलिस्ट काम कर रहा है...",
    bestHairstyles: "आपके लिए सबसे अच्छे हेयरस्टाइल", colorRec: "बालों के रंग की सिफारिश",
    stylesAvoid: "इन स्टाइल से बचें", groomingTips: "ग्रूमिंग टिप्स",
    dailyCalories: "दैनिक कैलोरी", macros: "दैनिक मैक्रोज़", proTips: "प्रो टिप्स",
    perfectOutfits: "आपके लिए परफेक्ट आउटफिट", colorPalette: "आपका रंग पैलेट",
    accessories: "जरूरी एक्सेसरीज", brands: "सुझाए गए ब्रांड",
    welcomeBack: "वापसी पर स्वागत", yourJourney: "यात्रा",
    notificationsTitle: "सूचनाएं", settingsTitle: "सेटिंग्स",
    darkMode: "डार्क मोड", lightMode: "लाइट मोड", language: "भाषा",
    workoutReminder: "वर्कआउट रिमाइंडर", waterReminder: "पानी रिमाइंडर", progressReport: "साप्ताहिक प्रगति रिपोर्ट",
    enabled: "चालू", disabled: "बंद",
    occasion: "अवसर चुनें", casual: "कैजुअल", office: "ऑफिस", party: "पार्टी", wedding: "शादी", gym: "जिम", date: "डेट नाइट",
    goal: "आपका लक्ष्य", weightLoss: "वजन घटाएं", muscle: "मांसपेशी बनाएं", weightGain: "वजन बढ़ाएं", maintenance: "फिट रहें",
    age: "उम्र", weight: "वजन", height: "ऊंचाई",
    signIn: "साइन इन", signUp: "साइन अप", createAccount: "🚀 अकाउंट बनाएं", signingIn: "कृपया प्रतीक्षा करें...",
    signOut: "🚪 साइन आउट", glowupMember: "✨ GlowUp सदस्य",
    faceAnalyses: "चेहरे के विश्लेषण", fitnessPlans: "फिटनेस प्लान", fashionLooks: "फैशन लुक",
    fitnessProfile: "फिटनेस प्रोफाइल",
  },
  pa: {
    appTagline: "ਸੁੰਦਰਤਾ · ਫਿਟਨੈਸ · ਫੈਸ਼ਨ",
    home: "ਹੋਮ", face: "ਚਿਹਰਾ", fitness: "ਫਿਟਨੈਸ", fashion: "ਫੈਸ਼ਨ", profile: "ਪ੍ਰੋਫਾਈਲ",
    faceTitle: "ਚਿਹਰੇ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ", faceSubtitle: "AI ਹੇਅਰਸਟਾਈਲ ਸੁਝਾਅ ਲਈ ਸੈਲਫੀ ਅਪਲੋਡ ਕਰੋ",
    fitnessTitle: "AI ਫਿਟਨੈਸ ਕੋਚ", fitnessSubtitle: "ਤੁਹਾਡੇ ਲਈ ਨਿੱਜੀ ਕੈਲੋਰੀ ਅਤੇ ਵਰਕਆਉਟ ਪਲਾਨ",
    fashionTitle: "AI ਫੈਸ਼ਨ ਸਲਾਹਕਾਰ", fashionSubtitle: "ਨਿੱਜੀ ਸਟਾਈਲ ਲਈ ਫੋਟੋ ਅਪਲੋਡ ਕਰੋ",
    uploadSelfie: "ਆਪਣੀ ਸੈਲਫੀ ਅਪਲੋਡ ਕਰੋ", uploadBody: "ਪੂਰੇ ਸਰੀਰ ਦੀ ਫੋਟੋ ਅਪਲੋਡ ਕਰੋ",
    analyzeBtn: "✨ ਚਿਹਰੇ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ", generateBtn: "🏋️ ਪਲਾਨ ਬਣਾਓ", styleBtn: "👗 ਸਟਾਈਲ ਕਰੋ",
    analyzing: "AI ਤੁਹਾਡੇ ਚਿਹਰੇ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰ ਰਿਹਾ ਹੈ...", building: "ਤੁਹਾਡਾ ਨਿੱਜੀ ਪਲਾਨ ਬਣ ਰਿਹਾ ਹੈ...", styling: "ਤੁਹਾਡਾ ਸਟਾਈਲਿਸਟ ਕੰਮ ਕਰ ਰਿਹਾ ਹੈ...",
    bestHairstyles: "ਤੁਹਾਡੇ ਲਈ ਸਭ ਤੋਂ ਵਧੀਆ ਹੇਅਰਸਟਾਈਲ", colorRec: "ਵਾਲਾਂ ਦੇ ਰੰਗ ਦੀ ਸਿਫਾਰਸ਼",
    stylesAvoid: "ਇਹ ਸਟਾਈਲ ਤੋਂ ਬਚੋ", groomingTips: "ਗਰੂਮਿੰਗ ਟਿਪਸ",
    dailyCalories: "ਰੋਜ਼ਾਨਾ ਕੈਲੋਰੀ", macros: "ਰੋਜ਼ਾਨਾ ਮੈਕਰੋਜ਼", proTips: "ਪ੍ਰੋ ਟਿਪਸ",
    perfectOutfits: "ਤੁਹਾਡੇ ਲਈ ਪਰਫੈਕਟ ਆਉਟਫਿਟ", colorPalette: "ਤੁਹਾਡਾ ਰੰਗ ਪੈਲੇਟ",
    accessories: "ਜ਼ਰੂਰੀ ਐਕਸੈਸਰੀਜ਼", brands: "ਸੁਝਾਏ ਗਏ ਬ੍ਰਾਂਡ",
    welcomeBack: "ਵਾਪਸੀ ਤੇ ਸੁਆਗਤ", yourJourney: "ਯਾਤਰਾ",
    notificationsTitle: "ਸੂਚਨਾਵਾਂ", settingsTitle: "ਸੈਟਿੰਗਾਂ",
    darkMode: "ਡਾਰਕ ਮੋਡ", lightMode: "ਲਾਈਟ ਮੋਡ", language: "ਭਾਸ਼ਾ",
    workoutReminder: "ਵਰਕਆਉਟ ਰਿਮਾਈਂਡਰ", waterReminder: "ਪਾਣੀ ਰਿਮਾਈਂਡਰ", progressReport: "ਹਫਤਾਵਾਰੀ ਪ੍ਰਗਤੀ ਰਿਪੋਰਟ",
    enabled: "ਚਾਲੂ", disabled: "ਬੰਦ",
    occasion: "ਮੌਕਾ ਚੁਣੋ", casual: "ਕੈਜੂਅਲ", office: "ਦਫਤਰ", party: "ਪਾਰਟੀ", wedding: "ਵਿਆਹ", gym: "ਜਿਮ", date: "ਡੇਟ ਨਾਈਟ",
    goal: "ਤੁਹਾਡਾ ਟੀਚਾ", weightLoss: "ਭਾਰ ਘਟਾਓ", muscle: "ਮਾਸਪੇਸ਼ੀ ਬਣਾਓ", weightGain: "ਭਾਰ ਵਧਾਓ", maintenance: "ਫਿੱਟ ਰਹੋ",
    age: "ਉਮਰ", weight: "ਭਾਰ", height: "ਕੱਦ",
    signIn: "ਸਾਈਨ ਇਨ", signUp: "ਸਾਈਨ ਅੱਪ", createAccount: "🚀 ਅਕਾਉਂਟ ਬਣਾਓ", signingIn: "ਕਿਰਪਾ ਉਡੀਕ ਕਰੋ...",
    signOut: "🚪 ਸਾਈਨ ਆਉਟ", glowupMember: "✨ GlowUp ਮੈਂਬਰ",
    faceAnalyses: "ਚਿਹਰੇ ਦੇ ਵਿਸ਼ਲੇਸ਼ਣ", fitnessPlans: "ਫਿਟਨੈਸ ਪਲਾਨ", fashionLooks: "ਫੈਸ਼ਨ ਲੁੱਕ",
    fitnessProfile: "ਫਿਟਨੈਸ ਪ੍ਰੋਫਾਈਲ",
  },
  ur: {
    appTagline: "خوبصورتی · فٹنس · فیشن",
    home: "ہوم", face: "چہرہ", fitness: "فٹنس", fashion: "فیشن", profile: "پروفائل",
    faceTitle: "چہرے کا تجزیہ", faceSubtitle: "AI ہیئر اسٹائل تجاویز کے لیے سیلفی اپلوڈ کریں",
    fitnessTitle: "AI فٹنس کوچ", fitnessSubtitle: "آپ کے لیے ذاتی کیلوری اور ورک آؤٹ پلان",
    fashionTitle: "AI فیشن مشیر", fashionSubtitle: "ذاتی اسٹائل کے لیے فوٹو اپلوڈ کریں",
    uploadSelfie: "اپنی سیلفی اپلوڈ کریں", uploadBody: "پورے جسم کی تصویر اپلوڈ کریں",
    analyzeBtn: "✨ چہرے کا تجزیہ کریں", generateBtn: "🏋️ پلان بنائیں", styleBtn: "👗 اسٹائل کریں",
    analyzing: "AI آپ کے چہرے کا تجزیہ کر رہا ہے...", building: "آپ کا ذاتی پلان بن رہا ہے...", styling: "آپ کا اسٹائلسٹ کام کر رہا ہے...",
    bestHairstyles: "آپ کے لیے بہترین ہیئر اسٹائل", colorRec: "بالوں کے رنگ کی سفارش",
    stylesAvoid: "ان اسٹائل سے بچیں", groomingTips: "گرومنگ ٹپس",
    dailyCalories: "روزانہ کیلوری", macros: "روزانہ میکروز", proTips: "پرو ٹپس",
    perfectOutfits: "آپ کے لیے بہترین آؤٹ فٹ", colorPalette: "آپ کا رنگ پیلیٹ",
    accessories: "ضروری اکسیسریز", brands: "تجویز کردہ برانڈ",
    welcomeBack: "واپسی پر خوش آمدید", yourJourney: "سفر",
    notificationsTitle: "اطلاعات", settingsTitle: "ترتیبات",
    darkMode: "ڈارک موڈ", lightMode: "لائٹ موڈ", language: "زبان",
    workoutReminder: "ورک آؤٹ یاددہانی", waterReminder: "پانی یاددہانی", progressReport: "ہفتہ وار پیشرفت رپورٹ",
    enabled: "چالو", disabled: "بند",
    occasion: "موقع منتخب کریں", casual: "کیژوئل", office: "دفتر", party: "پارٹی", wedding: "شادی", gym: "جم", date: "ڈیٹ نائٹ",
    goal: "آپ کا ہدف", weightLoss: "وزن کم کریں", muscle: "عضلات بنائیں", weightGain: "وزن بڑھائیں", maintenance: "فٹ رہیں",
    age: "عمر", weight: "وزن", height: "قد",
    signIn: "سائن ان", signUp: "سائن اپ", createAccount: "🚀 اکاؤنٹ بنائیں", signingIn: "براہ کرم انتظار کریں...",
    signOut: "🚪 سائن آؤٹ", glowupMember: "✨ GlowUp ممبر",
    faceAnalyses: "چہرے کے تجزیے", fitnessPlans: "فٹنس پلان", fashionLooks: "فیشن لکس",
    fitnessProfile: "فٹنس پروفائل",
  },
};

const LangContext = createContext(null);

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem("glowup_lang") || "en");
  const t = translations[lang] || translations.en;
  const changeLang = (l) => { setLang(l); localStorage.setItem("glowup_lang", l); };
  return <LangContext.Provider value={{ lang, t, changeLang }}>{children}</LangContext.Provider>;
}

export const useLang = () => useContext(LangContext);
